### ISSUE TITLE
intersect fails on not zero based index

### ISSUE THREAD

**Issue by felixlapalma** [EO-Forge/eo_tilematcher#2]
_Analysis_: It seems that indexes of dataframes should be reseted on load due to usage of iloc on geometric matching instead of loc. Check Failure [eo-tilematcher-101-Issue#1.zip](https://github.com/EO-Forge/eo_tilematcher/files/7305228/eo-tilematcher-101-Issue.1.zip)

In attached file a typo was made on Issue number (its 2 instead of 1)

**Comment by aperezhortal** [comment]
Closed by commit f080e6ec7451f70adff78b8a271d81658d398f50.
